###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: '3.1'
services:
    mysql:
        image: 'mysql:8.0'
        working_dir: /application
        #container_name: test_app2_mysql
        volumes:
            - '.:/application'
            - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
        environment:
            - MYSQL_ROOT_PASSWORD=123456
            - MYSQL_DATABASE=blogdb
            - MYSQL_USER=admin
            - MYSQL_PASSWORD=123456
        ports:
            - '30002:3306'

    webserver:
        image: 'nginx:alpine'
        working_dir: /application
        volumes:
            - '.:/application'
            - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '30000:80'
        depends_on:
            - php-fpm
        #restart: unless-stopped
        #links:
        #    - php-fpm

    php-fpm:
        build: phpdocker/php-fpm
        working_dir: /application
        container_name: test_app2_php-fpm
        volumes:
            - '.:/application'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini'
        depends_on:
            - mysql
        #links:
        #    - mysql

#Docker Networks
